name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        config:
        # [Python version, tox env]
        - ["3.8",   "py38"]
    runs-on: ubuntu-latest
    name: ${{ matrix.config[1] }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config[0] }}
    - name: Test env
      with:
        ADAPTER_SERVER: https://edgekoppeltaal.vhscloud.nl
        ADAPTER_DOMAIN: PythonAdapterTesting
        ADAPTER_USERNAME: ${{ secrets.ADAPTER_USERNAME }}
      run: echo "$ADAPTER_SERVER" "$ADAPTER_DOMAIN" "$ADAPTER_USERNAME"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      run: tox -e ${{ matrix.config[1] }}
