name: Run Koppeltaal Python Adapter tests
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        config:
        # [Python version, tox env]
        - ["3.8",   "py38"]
        - ["3.7",   "py37"]
        - ["3.6",   "py36"]
    runs-on: ubuntu-latest
    name: ${{ matrix.config[1] }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Pythonzope
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config[0] }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test runner
      env:
        ADAPTER_SERVER: https://edgekoppeltaal.vhscloud.nl
        ADAPTER_DOMAIN: PythonAdapterTesting
        ADAPTER_USERNAME: ${{ secrets.ADAPTER_USERNAME }}
        ADAPTER_PASSWORD: ${{ secrets.ADAPTER_PASSWORD }}
        ADAPTER_OAUTH_SECRET: ${{ secrets.ADAPTER_OAUTH_SECRET }}
      run: tox -e ${{ matrix.config[1] }} -- --html=test-report-${{ matrix.config[1] }}.html --self-contained-html
    - name: Test runner report
      uses: actions/upload-artifact@v1
      with:
        name: test-reports
        path: ./test-report-${{ matrix.config[1] }}.html

  owasp-scan:
    runs-on: ubuntu-latest
    steps:
    - name: OWASP dependency check
      run: |
        curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.5/dependency-check-6.0.5-release.zip > dependency-check-cli.zip
        unzip -q dependency-check-cli.zip
        dependency-check/bin/dependency-check.sh --project Koppeltaal-Java-Connector --out ./owasp-reports --format "HTML" --format "XML" --scan .
    - name: OWASP reports
      uses: actions/upload-artifact@v1
      with:
        name: OWASP-reports
        path: ./owasp-reports
