name: Run Koppeltaal Python Adapter tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        config:
        # [Python version, tox env]
        - ["3.8",   "py38"]
        - ["3.7",   "py37"]
        - ["3.6",   "py36"]
    runs-on: ubuntu-latest
    name: ${{ matrix.config[1] }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config[0] }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      env:
        ADAPTER_SERVER: https://edgekoppeltaal.vhscloud.nl
        ADAPTER_DOMAIN: PythonAdapterTesting
        ADAPTER_USERNAME: ${{ secrets.ADAPTER_USERNAME }}
        ADAPTER_PASSWORD: ${{ secrets.ADAPTER_PASSWORD }}
      run: tox -e ${{ matrix.config[1] }}
